spring:
  http:
    multipart:
    max-file-size: 5MB
    max-request-size: 20MB
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        format_sql: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE






