spring:
  active: local
  datasource:
    url: jdbc:mysql://localhost:3306/user?useSSL=false&useUnicode=yes&characterEncoding=utf-8&serverTimezone=UTC
    username: tlproject
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

